### ISSUE TITLE
Set can be slow

### ISSUE THREAD

**Issue by arj03** [xuset/idb-kv-store#27]
I'm storing rather large datasets in idb using this library. And I have noticed that because set broadcasts its set value even if not really used this tends to slow this quite a bit.

There doesn't seem to be a good [way](https://github.com/xuset/idb-kv-store/blob/d6ce0df94607da4ab1bebd70a0c78fdada5cb126/index.js#L31) to disable this so I'm looking for input on how to change this behaviour.

Thanks :)

**Comment by xuset** [comment]
Hey @arj03, yeah that is unfortunate. I'm thinking there's a few easy code changes that could be made to solve that. Maybe if `opts.channel` is explicitly set to `null` then that functionality should be disabled or possible just adding a new disable broadcasting like option to `opts`. Either way though, if you open a PR we can get those changes in

**Comment by arj03** [comment]
Thanks for your quick response @xuset. I have created a PR to resolve this issue.

**Comment by xuset** [comment]
Added in v4.5.0
